# Generated by Django 4.2.7 on 2024-01-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpin', '0002_hairpin_color_hairpin_name_hairpin_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='x', max_length=200)),
                ('title', models.CharField(default='x', max_length=200)),
                ('post', models.CharField(default='x', max_length=200)),
            ],
        ),
    ]
