# Generated by Django 4.2.7 on 2024-01-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairpin', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='mood',
        ),
    ]
