# Generated by Django 4.2.7 on 2024-01-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpin', '0004_rename_post_post_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='x', max_digits=10),
        ),
    ]
